#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

filetype="$( file -Lb --mime-type "$file")"


case "$filetype" in
    image*)
        kitten icat --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
        exit 1
        ;;
    video*)
        kitten icat --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(~/.config/lf/vidthumb "$file")" < /dev/null > /dev/tty
        exit 1
        ;;
    text*)
        head -n 100 "$file"
        exit 1
        ;;
esac